Repository 42-Gang/frontend, pull requests merged in 2025-06, with the labels that each got.

#196 feat(chat): 채팅 기능 추가
  src/App.tsx
  src/api/index.ts
  src/api/mutations/index.ts
  src/api/queries/index.ts
  src/api/queries/useChatDmRoomId.ts
  src/api/queries/useChatHistory.ts
  src/api/queryKey.ts
  src/api/socket/index.ts
  src/api/socket/socketEvents.ts
  src/api/socket/useChatSocket.ts
  src/api/types/chat.ts
  src/api/types/http.ts
  src/components/ui/back-button/index.tsx
  src/pages/FriendPage/ChatRoomPage/components/chat-box/index.tsx
  src/pages/FriendPage/ChatRoomPage/components/chat-box/styles.css.ts
  src/pages/FriendPage/ChatRoomPage/components/chat-friend-header/index.tsx
  src/pages/FriendPage/ChatRoomPage/components/chat-friend-header/styles.css.ts
  src/pages/FriendPage/ChatRoomPage/components/chat-friend-list/index.tsx
  src/pages/FriendPage/ChatRoomPage/components/chat-friend-list/styles.css.ts
  src/pages/FriendPage/ChatRoomPage/index.tsx
  src/pages/FriendPage/ChatRoomPage/styles.css.ts
  src/pages/FriendPage/components/friend-list/index.tsx
  src/styles/theme.css.ts
Labels: ✨ Feature, 📬 API

#197 feat(chat): 채팅 리스팅 방식 변경 및 토스트 액션 추가
  src/api/queries/useChatHistory.ts
  src/api/socket/useChatSocket.ts
  src/api/types/chat.ts
  src/pages/FriendPage/ChatRoomPage/components/chat-box/index.tsx
Labels: 📬 API, 🔨 Refactor

#203 feat: 비밀번호 유효성 검사 추가
  public/assets/images/check-circle.svg
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/styles.css.ts
Labels: ✨ Feature

#202 feat: Google OAuth 로그인 연동
  src/App.tsx
  src/api/mutations/useGoogleLogin.ts
  src/constants/routes.ts
  src/pages/SignInPage/GoogleCallbackPage/index.tsx
  src/pages/SignInPage/GoogleCallbackPage/styles.css.ts
  src/pages/SignInPage/index.tsx
  src/pages/index.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#207 refactor: 중복된 .env 변수 제거 및 VITE_API_URL로 통일
  package-lock.json
  src/pages/SignInPage/index.tsx
Labels: 🔨 Refactor

#209 feat: 1vs1 및 토너먼트 버튼에 이미지와 텍스트 UI 추가
  public/assets/images/1vs1.png
  public/assets/images/1vs1.svg
  public/assets/images/tournament.png
  src/pages/GameSelectPage/index.tsx
  src/pages/GameSelectPage/styles.css.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#211 refactor: sign in 에러 메세지 방식 변경, sign up password 관련 수정
  src/pages/SignInPage/EmailSignInPage/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/styles.css.ts
  src/styles/theme.css.ts
Labels: ✨ Feature

#216 feat: 비밀번호 힌트 툴팁 추가, 비밀번호 입력 확인 기능 추가, 비밀번호 유효성 확인 기능
  public/assets/images/show-password-false.png
  public/assets/images/show-password-true.png
  src/pages/SignUpPage/components/password-hint/index.tsx
  src/pages/SignUpPage/components/password-hint/styles.css.ts
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/styles.css.ts
  src/styles/theme.css.ts
Labels: ✨ Feature

#214 feat: 대기방(AUTO TOURNAMENT) 매칭 소켓 추가
  package.json
  pnpm-lock.yaml
  public/assets/images/tournament-random-profile.png
  src/components/ui/back-button/index.tsx
  src/pages/GameSelectPage/GameMatchingPage/AutoMatchingPage/AutoTournament/index.tsx
Labels: ✨ Feature, 📬 API
