Repository 42-Gang/frontend, pull requests merged in 2025-03, with the labels that each got.

#3 feat: Main home page complete
  Frontend/src/App.tsx
  Frontend/src/assets/fonts/Sixtyfour-Regular.ttf
  Frontend/src/assets/fonts/StWinterPixel24BoldDemoBold.otf
  Frontend/src/assets/image/1vs1.svg
  Frontend/src/assets/image/Bullet.svg
  Frontend/src/assets/image/Button_Back.svg
  Frontend/src/assets/image/Button_Change_NickName.svg
  Frontend/src/assets/image/Button_Change_Profile.svg
  Frontend/src/assets/image/Button_GameMode_Off.svg
  Frontend/src/assets/image/Button_GameMode_On.svg
  Frontend/src/assets/image/Button_GameOption_Off.svg
  Frontend/src/assets/image/Button_GameOption_On.svg
  Frontend/src/assets/image/Button_History_Off.svg
  Frontend/src/assets/image/Button_History_On.svg
  Frontend/src/assets/image/Button_LogOut_Off.svg
  Frontend/src/assets/image/Button_LogOut_On.svg
  Frontend/src/assets/image/CheckCircle.svg
  Frontend/src/assets/image/Display_1vs1.svg
  Frontend/src/assets/image/Display_Tournament.svg
  Frontend/src/assets/image/NO.svg
  Frontend/src/assets/image/ProfileSection_InSetting.svg
  Frontend/src/assets/image/Selection.svg
  Frontend/src/assets/image/Tournament.svg
  Frontend/src/assets/image/YES.svg
  Frontend/src/index.css
  Frontend/src/pages/History_1vs1.tsx
  Frontend/src/pages/History_Home.tsx
  Frontend/src/pages/History_Tournament.tsx
  Frontend/src/pages/Home.tsx
  Frontend/src/pages/Login.tsx
  Frontend/src/pages/Register.tsx
  Frontend/src/pages/Select_GameMode_Auto.tsx
  Frontend/src/pages/Select_GameMode_Custom.tsx
  Frontend/src/pages/Select_GameOption.tsx
  Frontend/src/pages/Setting.tsx
  Frontend/src/pages/WatingRoom_1vs1_Auto.tsx
  Frontend/src/pages/WatingRoom_1vs1_Custom.tsx
  Frontend/src/pages/WatingRoom_Tournament_Auto.tsx
  Frontend/src/pages/WatingRoom_Tournament_Custom.tsx
Labels: ✨ Feature

#4 feat: 토너먼트 공통 컴포넌트
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/assets/fonts/Sixtyfour.ttf
  Frontend/src/assets/image/BasicProfile1.png
  Frontend/src/assets/image/BasicProfile1.svg
  Frontend/src/assets/image/BasicProfile2.png
  Frontend/src/assets/image/ReadyButton.png
  Frontend/src/pages/Tournament/Tournament.ts
  Frontend/src/pages/Tournament/Tournament.tsx
  Frontend/src/pages/Tournament/Waiting.ts
  Frontend/src/pages/Tournament/Waiting.tsx
  Frontend/src/styles/GlobalStyles.ts
Labels: ✨ Feature

#6 feat: Setting 홈페이지 팝업 구현 완료
  Frontend/src/App.tsx
  Frontend/src/assets/fonts/Inter.ttf
  Frontend/src/assets/image/Button_Close_NickNamePopUp.svg
  Frontend/src/components/Setting/ChangeNickNamePopup.tsx
  Frontend/src/components/Setting/ChangeProfilePopup.tsx
  Frontend/src/components/Setting/ConfirmLogOutPopup.tsx
  Frontend/src/index.css
  Frontend/src/pages/GameHistory/History_Home.tsx
  Frontend/src/pages/GameSelect/Select_GameMode_Auto.tsx
  Frontend/src/pages/GameSelect/Select_GameMode_Custom.tsx
  Frontend/src/pages/GameSelect/Select_GameOption.tsx
  Frontend/src/pages/History_1vs1.tsx
  Frontend/src/pages/History_Home.tsx
  Frontend/src/pages/History_Tournament.tsx
  Frontend/src/pages/Main/Home.tsx
  Frontend/src/pages/Main/Login.tsx
  Frontend/src/pages/Main/Register.tsx
  Frontend/src/pages/Setting.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/WatingRoom_1vs1_Auto.tsx
  Frontend/src/pages/WatingRoom_1vs1_Custom.tsx
  Frontend/src/pages/WatingRoom_Tournament_Auto.tsx
  Frontend/src/pages/WatingRoom_Tournament_Custom.tsx
Labels: ✨ Feature

#7 feat: 토너먼트 친구 초대
  .DS_Store
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/assets/image/InviteButton.svg
  Frontend/src/assets/image/InviteIcon.svg
  Frontend/src/assets/image/InvitedButton.svg
  Frontend/src/assets/image/ModalCancel.svg
  Frontend/src/pages/Tournament/Invitation.ts
  Frontend/src/pages/Tournament/Invitation.tsx
  Frontend/src/pages/Tournament/Tournament.ts
  Frontend/src/pages/Tournament/Tournament.tsx
  Frontend/src/pages/Tournament/Waiting.ts
  Frontend/vite.config.ts
Labels: ✨ Feature

#10 feat: History 페이지 구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/assets/image/ButtonBack.svg
  Frontend/src/assets/image/ButtonChangeAvatarImg.svg
  Frontend/src/assets/image/ButtonChangeNickname.svg
  Frontend/src/assets/image/ButtonCloseNicknamePopup.svg
  Frontend/src/assets/image/ButtonGameModeOff.svg
  Frontend/src/assets/image/ButtonGameModeOn.svg
  Frontend/src/assets/image/ButtonGameOptionOff.svg
  Frontend/src/assets/image/ButtonGameOptionOn.svg
  Frontend/src/assets/image/ButtonHistoryOff.svg
  Frontend/src/assets/image/ButtonHistoryOn.svg
  Frontend/src/assets/image/ButtonLogOutOff.svg
  Frontend/src/assets/image/ButtonLogOutOn.svg
  Frontend/src/assets/image/ButtonVerifyOff.svg
  Frontend/src/assets/image/ButtonVerifyOn.svg
  Frontend/src/assets/image/Display_1vs1.svg
  Frontend/src/assets/image/Display_Tournament.svg
  Frontend/src/assets/image/ProfileSection_InSetting.svg
  Frontend/src/components/Setting/ChangeNickNamePopup.tsx
  Frontend/src/components/Setting/ChangeProfilePopup.tsx
  Frontend/src/components/Setting/ConfirmLogOutPopup.tsx
  Frontend/src/components/gameHistory/GameRecord.tsx
  Frontend/src/components/gameHistory/ModeSelector.tsx
  Frontend/src/components/gameHistory/TotalWins.tsx
  Frontend/src/components/gameHistory/WinLossCounter.tsx
  Frontend/src/components/setting/ChangeAvatarPopup.tsx
  Frontend/src/components/setting/ChangeNicknamePopup.tsx
  Frontend/src/components/setting/ConfirmLogoutPopup.tsx
  Frontend/src/pages/GameHistory/History_Home.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/gameHistory/History_Home.tsx
  Frontend/src/pages/gameSelect/Select_GameMode_Auto.tsx
  Frontend/src/pages/gameSelect/Select_GameMode_Custom.tsx
  Frontend/src/pages/gameSelect/Select_GameOption.tsx
  Frontend/src/pages/main/Home.tsx
  Frontend/src/pages/main/Login.tsx
  Frontend/src/pages/main/Register.tsx
  Frontend/src/pages/setting/Setting.tsx
  Frontend/src/styles/GlobalStyles.ts
  Frontend/tsconfig.app.json
Labels: ✨ Feature

#11 refactor: Overall code modification
  Frontend/src/App.tsx
  Frontend/src/components/gameHistory/GameRecord.tsx
  Frontend/src/components/gameHistory/ModeSelector.tsx
  Frontend/src/components/gameHistory/TotalWins.tsx
  Frontend/src/components/gameHistory/WinLossCounter.tsx
  Frontend/src/components/setting/ChangeAvatarPopup.tsx
  Frontend/src/components/setting/ChangeNicknamePopup.tsx
  Frontend/src/components/setting/ConfirmLogoutPopup.tsx
  Frontend/src/pages/gameHistory/History_Home.tsx
  Frontend/src/pages/gameSelect/Select_GameMode_Auto.tsx
  Frontend/src/pages/gameSelect/Select_GameMode_Custom.tsx
  Frontend/src/pages/gameSelect/Select_GameOption.tsx
  Frontend/src/pages/main/Home.tsx
  Frontend/src/pages/main/Login.tsx
  Frontend/src/pages/main/Register.tsx
  Frontend/src/pages/setting/Setting.tsx
Labels: 🔨 Refactor

#12 style: 스크롤바 디자인 변경
  Frontend/package-lock.json
  Frontend/src/pages/Tournament/Invitation.ts
Labels: 🎨 Html&css

#13 feat: 토너먼트 대진 결과 메인
  Frontend/src/App.tsx
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
Labels: ✨ Feature

#14 feat: 2강 승자 프로필 및 VS 텍스트 UI 추가
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
Labels: ✨ Feature

#20 feat: Game 페이지 구현
  Frontend/src/App.tsx
  Frontend/src/assets/image/ButtonMenu.svg
  Frontend/src/assets/image/GameBall.svg
  Frontend/src/components/game/Popup/GameMenuPopup.tsx
  Frontend/src/components/game/Score.tsx
  Frontend/src/components/game/gameField/Ball.tsx
  Frontend/src/components/game/gameField/Field.tsx
  Frontend/src/components/game/gameField/Paddle.tsx
  Frontend/src/pages/game/GameScreen.tsx
  Frontend/src/pages/gameHistory/History_Home.tsx
Labels: ✨ Feature

#22 Update issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: 📃 Docs

#25 refactor: 토너먼트 페이지 컴포넌트 분리
  Frontend/src/pages/Tournament/MatchResult.tsx
  Frontend/src/pages/Tournament/Matching.tsx
  Frontend/src/pages/Tournament/components/FinalResultDisplay.tsx
  Frontend/src/pages/Tournament/components/FourUsersGrid.tsx
  Frontend/src/pages/Tournament/components/MatchLines.tsx
  Frontend/src/pages/Tournament/components/SemiFinalGrid.tsx
  Frontend/src/pages/Tournament/components/UserProfileCard.tsx
Labels: 🔨 Refactor

#27 refactor: 토너먼트 대진표 라인 컴포넌트 분리 및 스타일 상수화
  Frontend/src/App.tsx
  Frontend/src/pages/Tournament/LineConstants.ts
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
  Frontend/src/pages/Tournament/Waiting.ts
  Frontend/src/pages/Tournament/Waiting.tsx
  Frontend/src/pages/Tournament/components/FourUsersGrid.tsx
  Frontend/src/pages/Tournament/components/MatchLines.tsx
  Frontend/src/pages/Tournament/components/SemiFinalGrid.tsx
Labels: 🔨 Refactor

#28 refactor: 토너먼트 파일 구조 변경
  Frontend/src/pages/Tournament/FinalResultDisplay/FinalResultDisplay.styles.ts
  Frontend/src/pages/Tournament/FinalResultDisplay/index.tsx
  Frontend/src/pages/Tournament/Invitation.tsx
  Frontend/src/pages/Tournament/MatchResult.tsx
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
  Frontend/src/pages/Tournament/components/FinalResultDisplay.tsx
  Frontend/src/pages/Tournament/components/FourUsersGrid.tsx
  Frontend/src/pages/Tournament/components/FourUsersGrid/FourUsersGrid.styles.ts
  Frontend/src/pages/Tournament/components/FourUsersGrid/index.tsx
  Frontend/src/pages/Tournament/components/SemiFinalGrid.tsx
  Frontend/src/pages/Tournament/components/SemiFinalGrid/SemiFinalGrid.styles.ts
  Frontend/src/pages/Tournament/components/SemiFinalGrid/index.tsx
  Frontend/src/pages/Tournament/components/UserProfileCard.tsx
  Frontend/src/pages/Tournament/components/UserProfileCard/UserProfileCard.styles.ts
  Frontend/src/pages/Tournament/components/UserProfileCard/index.tsx
  Frontend/src/pages/Tournament/types/User.ts
Labels: 🔨 Refactor

#32 refactor: MatchResult.tsx 기능을 Matching.tsx로 통합하여 중복 제거
  Frontend/src/App.tsx
  Frontend/src/pages/Tournament/MatchResult.ts
  Frontend/src/pages/Tournament/MatchResult.tsx
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
  Frontend/src/pages/Tournament/components/SemiFinalGrid/index.tsx
  Frontend/src/pages/Tournament/components/UserProfileCard/UserProfileCard.styles.ts
  Frontend/src/pages/Tournament/components/UserProfileCard/index.tsx
Labels: 🔨 Refactor

#34 refactor: App.tsx 오류 해결
  Frontend/package-lock.json
  Frontend/src/App.tsx
Labels: 🔨 Refactor

#35 feat: 버튼 애니메이션 추가
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/assets/image/HistoryButtonOff.png
  Frontend/src/assets/image/HistoryButtonOff.svg
  Frontend/src/assets/image/HistoryButtonOn.png
  Frontend/src/assets/image/HistoryButtonOn.svg
  Frontend/src/assets/image/VerifyButtonOff.png
  Frontend/src/assets/image/VerifyButtonOff.svg
  Frontend/src/assets/image/VerifyButtonOn.png
  Frontend/src/assets/image/VerifyButtonOn.svg
  Frontend/src/pages/GameHistory/components/ModeSelector.tsx
  Frontend/src/pages/Register/components/Verify.tsx
Labels: ✨ Feature

#36 feat: 상대방 Ready 상태 반영 및 Toast 표시
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
Labels: ✨ Feature
