Repository 42-Gang/frontend, pull requests merged in 2025-04, with the labels that each got.

#38 refactor: 리뷰에서 지적받은 부분 리펙토링
  Frontend/src/pages/Game/GameScreen.tsx
  Frontend/src/pages/Game/components/Field.tsx
  Frontend/src/pages/Game/components/MenuPopup.tsx
  Frontend/src/pages/GameHistory/GameHistory.tsx
  Frontend/src/pages/GameHistory/components/GameRecord.tsx
  Frontend/src/pages/GameHistory/components/ModeSelector.tsx
  Frontend/src/pages/GameHistory/components/WinLossCounter.tsx
  Frontend/src/pages/Register/components/Cancel.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
  Frontend/src/pages/Setting/ConfirmLogout.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Setting/components/ChangeProfilePopup.tsx
  Frontend/src/pages/Setting/components/ConfirmLogoutPopup.tsx
  Frontend/src/pages/Setting/components/Profile.tsx
  Frontend/src/pages/Setting/components/UserInformation.tsx
Labels: 🔨 Refactor

#43 Refactor: 탭 스페이스 간격 조절
  Frontend/src/pages/Game/GameScreen.tsx
  Frontend/src/pages/Game/components/Ball.tsx
  Frontend/src/pages/Game/components/Container.tsx
  Frontend/src/pages/Game/components/Field.tsx
  Frontend/src/pages/Game/components/MenuPopup.tsx
  Frontend/src/pages/Game/components/Paddle.tsx
  Frontend/src/pages/Game/components/Score.tsx
  Frontend/src/pages/GameHistory/GameHistory.tsx
  Frontend/src/pages/GameHistory/components/Cancel.tsx
  Frontend/src/pages/GameHistory/components/Container.tsx
  Frontend/src/pages/GameHistory/components/GameRecord.tsx
  Frontend/src/pages/GameHistory/components/ModeSelector.tsx
  Frontend/src/pages/GameHistory/components/TotalWinsCounter.tsx
  Frontend/src/pages/GameHistory/components/WinLossCounter.tsx
  Frontend/src/pages/GameModeSelect/AutoGameModeSelect.tsx
  Frontend/src/pages/GameModeSelect/CustomGameModeSelect.tsx
  Frontend/src/pages/GameModeSelect/components/Cancel.tsx
  Frontend/src/pages/GameModeSelect/components/Container.tsx
  Frontend/src/pages/GameModeSelect/components/MainTitle.tsx
  Frontend/src/pages/GameModeSelect/components/SelectMode.tsx
  Frontend/src/pages/GameOptionSelect/GameOptionSelect.tsx
  Frontend/src/pages/GameOptionSelect/components/ActionButton.tsx
  Frontend/src/pages/GameOptionSelect/components/Container.tsx
  Frontend/src/pages/GameOptionSelect/components/Credit.tsx
  Frontend/src/pages/GameOptionSelect/components/MainTitle.tsx
  Frontend/src/pages/Home/Home.tsx
  Frontend/src/pages/Home/components/ActionButton.tsx
  Frontend/src/pages/Home/components/Cancel.tsx
  Frontend/src/pages/Home/components/Container.tsx
  Frontend/src/pages/Home/components/Credit.tsx
  Frontend/src/pages/Home/components/MainTitle.tsx
  Frontend/src/pages/Login/Login.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/Container.tsx
  Frontend/src/pages/Login/components/Credit.tsx
  Frontend/src/pages/Login/components/InputField.tsx
  Frontend/src/pages/Login/components/MainTitle.tsx
  Frontend/src/pages/Register/Register.tsx
  Frontend/src/pages/Register/components/Cancel.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Container.tsx
  Frontend/src/pages/Register/components/Credit.tsx
  Frontend/src/pages/Register/components/InputField.tsx
  Frontend/src/pages/Register/components/MainTitle.tsx
  Frontend/src/pages/Register/components/Verify.tsx
  Frontend/src/pages/Setting/ConfirmLogout.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/Cancel.tsx
  Frontend/src/pages/Setting/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Setting/components/ChangeProfilePopup.tsx
  Frontend/src/pages/Setting/components/ConfirmLogoutPopup.tsx
  Frontend/src/pages/Setting/components/Container.tsx
  Frontend/src/pages/Setting/components/Profile.tsx
  Frontend/src/pages/Setting/components/UserInformation.tsx
Labels: 🔨 Refactor

#39 feat: 토너먼트 4강 대기 상태 표시 및 화면 이동
  Frontend/src/App.tsx
  Frontend/src/assets/image/BlueMask.svg
  Frontend/src/assets/image/RedMask.svg
  Frontend/src/pages/Tournament/Matching.ts
  Frontend/src/pages/Tournament/Matching.tsx
  Frontend/src/pages/Tournament/SemiFinalWaiting.tsx
  Frontend/src/pages/Tournament/components/FinalResultDisplay.tsx
  Frontend/src/pages/Tournament/components/MatchUserOverlayCard/MatchUserOverlayCard.styles.ts
  Frontend/src/pages/Tournament/components/MatchUserOverlayCard/index.tsx
  Frontend/src/pages/Tournament/components/UserProfileCard/index.tsx
  Frontend/src/styles/toastStyles.ts
Labels: ✨ Feature

#45 fix: GameScreen에서 돌아온 경우에만 승자 텍스트 표시
  Frontend/src/pages/Game/GameScreen.tsx
  Frontend/src/pages/SoloMatch/SoloMatch.tsx
  Frontend/src/pages/SoloMatch/components/SoloMatchGrid/index.tsx
Labels: 🐞 BugFix

#46 feat: Login 페이지 mock 추가
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/assets/fonts/Galmuri7.ttf
  Frontend/src/index.css
  Frontend/src/pages/Login/Login.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/Container.tsx
  Frontend/src/pages/Login/components/Credit.tsx
  Frontend/src/pages/Login/components/ErrorMessage.tsx
  Frontend/src/pages/Login/components/InputField.tsx
  Frontend/src/pages/Login/components/MainTitle.tsx
  Frontend/src/pages/Register/components/InputField.tsx
Labels: ✨ Feature

#48 feat: GameScreen 방향키 이동, 데이터 받아 해당 위치에 패들 구현
  Frontend/src/assets/image/BallBullet.svg
  Frontend/src/assets/image/GiveupButtonOn.png
  Frontend/src/pages/Game/GameScreen.tsx
  Frontend/src/pages/Game/components/Ball.tsx
  Frontend/src/pages/Game/components/Field.tsx
  Frontend/src/pages/Game/components/GameCanvas.tsx
  Frontend/src/pages/Game/components/Giveup.tsx
  Frontend/src/pages/Game/components/GiveupPopup.tsx
  Frontend/src/pages/Game/components/Paddle.tsx
  Frontend/src/pages/Game/components/Score.tsx
Labels: ✨ Feature

#49 feat: 카운트다운, 듀스 알림, 우승자 알림 팝업 추가
  Frontend/src/pages/Game/GameScreen.tsx
  Frontend/src/pages/Game/components/Animation.tsx
  Frontend/src/pages/Game/components/GameCanvas.tsx
  Frontend/src/pages/Game/components/GameOverPopup.tsx
  Frontend/src/pages/Game/components/Giveup.tsx
  Frontend/src/pages/Game/components/Score.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
Labels: ✨ Feature

#51 feat: Friend List 페이지 UI 작업
  Frontend/src/App.tsx
  Frontend/src/assets/image/AddFriendIcon.svg
  Frontend/src/assets/image/AlarmIcon.svg
  Frontend/src/assets/image/Magnifier.svg
  Frontend/src/assets/image/MessageIcon.svg
  Frontend/src/pages/FriendList/FriendList.tsx
  Frontend/src/pages/FriendList/components/AddFriend.tsx
  Frontend/src/pages/FriendList/components/Alarm.tsx
  Frontend/src/pages/FriendList/components/Cancel.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/Container.tsx
  Frontend/src/pages/FriendList/components/LinkState.tsx
  Frontend/src/pages/FriendList/components/Message.tsx
  Frontend/src/pages/FriendList/components/SearchFriend.tsx
  Frontend/src/pages/Login/components/ErrorMessage.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/ConfirmLogout.tsx
Labels: ✨ Feature

#53 feat: Friend List 페이지 친구 추가 팝업, 상태표시, 친구 검색 기능 추가
  Frontend/src/assets/image/AvailableAddFriend.svg
  Frontend/src/assets/image/CompletedAddFriend.svg
  Frontend/src/assets/image/MagnifierAddFriend.svg
  Frontend/src/pages/FriendList/FriendList.tsx
  Frontend/src/pages/FriendList/components/AddFriend.tsx
  Frontend/src/pages/FriendList/components/AddFriendPopup.tsx
  Frontend/src/pages/FriendList/components/Animation.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/FriendSection.tsx
  Frontend/src/pages/FriendList/components/LinkState.tsx
  Frontend/src/pages/FriendList/components/SearchFriend.tsx
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
Labels: ✨ Feature

#55 refactor: API mock, 회원 가입 버튼 수정
  Frontend/mock_server/package-lock.json
  Frontend/mock_server/package.json
  Frontend/mock_server/server.cjs
  Frontend/package-lock.json
  Frontend/public/mockServiceWorker.js
  Frontend/src/pages/Login/Login.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/Animation.tsx
  Frontend/src/pages/Login/components/ErrorMessage.tsx
  Frontend/src/pages/Login/components/MainTitle.tsx
  Frontend/src/pages/Login/components/useLogin.ts
Labels: ✨ Feature

#60 feat: 구글 관련 로그인 옵션 추가
  Frontend/src/pages/Login/Login.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/MainTitle.tsx
  Frontend/src/pages/Register/components/MainTitle.tsx
Labels: ✨ Feature

#66 feat: 입력값에 따른 알림창
  Frontend/mock_server/server.cjs
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Register/RegisterWithEmail.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/InputField.tsx
  Frontend/src/pages/Register/components/Verify.tsx
Labels: ✨ Feature

#67 feat: API 요청 시 토큰의 유효성을 확인하는 공통 로직 작성
  Frontend/mock_server/package-lock.json
  Frontend/mock_server/package.json
  Frontend/mock_server/server.cjs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/pages/Home/Home.tsx
  Frontend/src/pages/Home/components/ActionButton.tsx
  Frontend/src/pages/Home/components/Cancel.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/Animation.tsx
  Frontend/src/pages/Setting/components/ConfirmLogout.tsx
  Frontend/src/pages/Setting/components/Profile.tsx
  Frontend/src/pages/Setting/components/UserInformation.tsx
  Frontend/src/utils/authFetch.ts
  Frontend/vite.config.ts
Labels: 📬 API

#69 feat: Register 페이지 API 적용
  Frontend/mock_server/server.cjs
  Frontend/src/assets/image/Completed.svg
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
  Frontend/src/pages/Register/RegisterWithEmail.tsx
  Frontend/src/pages/Register/components/CheckInvalid.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
Labels: 📬 API

#71 feat: Setting 페이지 API 적용
  Frontend/mock_server/server.cjs
  Frontend/src/pages/Register/RegisterWithEmail.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Setting/components/ChangeProfilePopup.tsx
  Frontend/src/pages/Setting/components/ConfirmLogoutPopup.tsx
  Frontend/src/pages/Setting/components/Profile.tsx
  Frontend/uploads/0535d90d93103dfd8fb0115a3279cfe2
  Frontend/uploads/05ab596b1c10a2c920e03fd23392e827
  Frontend/uploads/07b296dc163f69f5f74e1e571acb9101
  Frontend/uploads/0f2e648d8fea2516c9741f314a9453a1
  Frontend/uploads/4569a302d8266259d9c52b1ba70f1cd8
  Frontend/uploads/4f32763133f2b8962722fb24f6ecb7b5
  Frontend/uploads/5cfd9b505d568ec33db9475d3fdf122d
  Frontend/uploads/5d089a2d160f559d21221851028ae170
  Frontend/uploads/5d70bb810c3d8e083719df665b616c31
  Frontend/uploads/6bbb70dab8d14fdd7f0448d2d6e0af84
  Frontend/uploads/8baa80f703c4b265be39d1cdc4841631
  Frontend/uploads/a520595a84cc4fd68bcb1d0cf215ef10
  Frontend/uploads/c6a993cafaf25f65febedb5a1eb555c5
  Frontend/uploads/c857f019f62aadf632c666c87ddcd10d
  Frontend/uploads/d9dd8faa1fa5c3bdcf7448e5082a8125
  Frontend/uploads/d9f56df04c0bd292511e3fdf327ccd28
  Frontend/uploads/da41f8ec6dcfe47f150b3076d6c9fa39
  Frontend/uploads/de5779b8aa0fb21418d2042068c11bb1
  Frontend/uploads/e4e7ff7e1ecd79ebb576188f482be514
  Frontend/uploads/e78cb634d2a0774a473a5d579c65f9bc
  Frontend/uploads/f8905525ef9507fcc6b75c0cb598c7a3
  Frontend/uploads/fba1c7c507ee8bfa1a85c1b82edb3c1d
Labels: ✨ Feature, 📬 API

#75 [refactor] mock server 리팩토링
  Frontend/mock_server/controllers/authController.cjs
  Frontend/mock_server/controllers/gameController.cjs
  Frontend/mock_server/controllers/userController.cjs
  Frontend/mock_server/data/users.cjs
  Frontend/mock_server/middlewares/authMiddleware.cjs
  Frontend/mock_server/routes/authRoutes.cjs
  Frontend/mock_server/routes/gameRoutes.cjs
  Frontend/mock_server/routes/userRoutes.cjs
  Frontend/mock_server/server.cjs
  Frontend/mock_server/utils/jwtUtils.cjs
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/uploads/aacbbdc756c4bcd51ea42e8fd8b0aab9
Labels: ✨ Feature, 📬 API

#77 FriendList 1:1 채팅 WebSocket IO 연동
  Frontend/env.example
  Frontend/mock/server.cjs
  Frontend/mock/socket/FriendChat.cjs
  Frontend/mock/socket/UserInfo.cjs
  Frontend/mock/socket/tournamentHandler.cjs
  Frontend/mockServer.cjs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/api/chat.ts
  Frontend/src/api/friends.ts
  Frontend/src/main.tsx
  Frontend/src/pages/FriendList/FriendChatRoom.ts
  Frontend/src/pages/FriendList/FriendChatRoom.tsx
  Frontend/src/pages/FriendList/components/UserProfileModal.styles.ts
  Frontend/src/pages/FriendList/components/UserProfileModal.tsx
  Frontend/src/pages/Tournament/Invitation.ts
  Frontend/src/pages/Tournament/Invitation.tsx
  Frontend/src/socket/socket.ts
  Frontend/vite.config.ts
Labels: 📬 API

#76 feat: env 환경 변수 작업
  Frontend/src/pages/GameHistory/GameHistory.tsx
  Frontend/src/pages/Home/components/ActionButton.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Register/components/CheckInvalid.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Setting/components/ConfirmLogoutPopup.tsx
  Frontend/src/pages/Setting/components/Profile.tsx
  Frontend/src/utils/authFetch.ts
Labels: 🔨 Refactor

#81 fix: Register API 엔드포인트 수정
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
Labels: 🐞 BugFix, 📬 API

#83 feat: accessToken 검사하여 Home 페이지 유지하는 기능 추가
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/pages/FriendList/components/AddFriendPopup.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/FriendSection.tsx
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
  Frontend/src/pages/Game/components/GiveupPopup.tsx
  Frontend/src/pages/GameHistory/GameHistory.tsx
  Frontend/src/pages/GameModeSelect/AutoGameModeSelect.tsx
  Frontend/src/pages/GameModeSelect/CustomGameModeSelect.tsx
  Frontend/src/pages/GameModeSelect/components/MainTitle.tsx
  Frontend/src/pages/GameModeSelect/components/SelectMode.tsx
  Frontend/src/pages/GameOptionSelect/GameOptionSelect.tsx
  Frontend/src/pages/GameOptionSelect/components/MainTitle.tsx
  Frontend/src/pages/Home/Home.tsx
  Frontend/src/pages/Home/components/MainTitle.tsx
  Frontend/src/pages/Login/Login.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Register/components/CheckInvalid.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
  Frontend/src/pages/Setting/Setting.tsx
  Frontend/src/pages/Setting/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Setting/components/ConfirmLogoutPopup.tsx
  Frontend/src/pages/Setting/components/Profile.tsx
  Frontend/src/utils/authFetch.ts
  Frontend/uploads/69f6ef59f1e28d71a4d904dc89b385b1
  Frontend/uploads/90d6d1e89295e68365b84e802c6d7368
  Frontend/uploads/a61b7a7c8c2836d79b21fbf8cfbbfdb3
  Frontend/uploads/aacbbdc756c4bcd51ea42e8fd8b0aab9
  Frontend/uploads/cbfe0102f504ddf17eedb885766885f2
Labels: ✨ Feature, 📬 API

#85 feat : 친구 목록, 친구 요청 목록, 거절, 승인, 친구 검색 기능 추가
  Frontend/.gitignore
  Frontend/package.json
  Frontend/src/pages/FriendList/FriendList.tsx
  Frontend/src/pages/FriendList/components/AddFriend.tsx
  Frontend/src/pages/FriendList/components/AddFriendPopup.tsx
  Frontend/src/pages/FriendList/components/Alarm.tsx
  Frontend/src/pages/FriendList/components/AlarmPopup.tsx
  Frontend/src/pages/FriendList/components/Cancel.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Register/components/CheckInvalid.tsx
  Frontend/src/pages/Register/components/Verify.tsx
Labels: ✨ Feature, 📬 API

#86 fix: Login, Register 수정 사항 되돌림
  Frontend/src/pages/Login/Login.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Register/components/CheckInvalid.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
  Frontend/src/utils/authFetch.ts
Labels: 🐞 BugFix

#87 feat: Login error message 출력 방식 설정
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/utils/authFetch.ts
Labels: 🔨 Refactor

#89 [REFACTOR] 친구관련 수정
  Frontend/src/pages/FriendList/components/AddFriendPopup.tsx
  Frontend/src/pages/FriendList/components/AlarmPopup.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/utils/authFetch.ts
Labels: 🔨 Refactor

#91 feat: 유저 Information 조회, 유저 닉네임, 프로필 사진 변경, 로그아웃 API 구현
  Frontend/.gitignore
  Frontend/src/pages/Profile/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Profile/components/ConfirmLogoutPopup.tsx
  Frontend/src/pages/Profile/components/Profile.tsx
  Frontend/src/utils/authFetch.ts
Labels: ✨ Feature, 📬 API

#96 fix: 친구 리스트 조회 안 되는 버그 수정
  Frontend/src/pages/FriendList/FriendList.tsx
  Frontend/src/pages/FriendList/components/AlarmPopup.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/FriendSection.tsx
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
  Frontend/src/pages/Login/components/useLogin.ts
  Frontend/src/pages/Profile/components/ChangeNicknamePopup.tsx
  Frontend/src/pages/Profile/components/ChangeProfilePopup.tsx
  Frontend/src/pages/Register/components/Confirm.tsx
  Frontend/src/pages/Register/components/Verify.tsx
  Frontend/src/socket/socket.ts
  Frontend/src/utils/authFetch.ts
Labels: 🐞 BugFix, 📬 API

#97 fix:친구 요청 승인, 거절 시 빈 body 보내도록 수정, body key명 수정
  Frontend/src/pages/FriendList/components/AddFriendPopup.tsx
  Frontend/src/pages/FriendList/components/AlarmPopup.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/SearchResultCard.tsx
  Frontend/src/utils/authFetch.ts
Labels: 🐞 BugFix, 📬 API

#90 refactor: websocket 통신
  Frontend/mock/utils/token.ts
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/api/axiosInstance.ts
  Frontend/src/api/chat.ts
  Frontend/src/api/friends.ts
  Frontend/src/pages/FriendList/FriendChatRoom.tsx
  Frontend/src/pages/FriendList/components/FriendListItem.styles.ts
  Frontend/src/pages/FriendList/components/FriendListItem.tsx
  Frontend/src/socket/socket.ts
  Frontend/src/utils/decodeToken.ts
  Frontend/src/utils/getAccessToken.ts
  package-lock.json
Labels: ✨ Feature, 📬 API

#98 feat: 로그인 시 Web Socket 연결, 로그아웃 시 Web Socket 연결 해제 추가, Web Socket으로 유저 상태 추적 구현, 메세지 아이콘 클릭 시 채팅창 띄우기 구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/contexts/WebSocketContext.tsx
  Frontend/src/contexts/WebSocketProvider.tsx
  Frontend/src/main.tsx
  Frontend/src/pages/FriendList/components/ContactList.tsx
  Frontend/src/pages/FriendList/components/FriendStatusAtom.ts
  Frontend/src/pages/FriendList/components/LinkState.tsx
  Frontend/src/pages/FriendList/components/Message.tsx
  Frontend/src/pages/Login/components/ActionButton.tsx
  Frontend/src/pages/Login/hooks/useLogin.ts
  Frontend/src/pages/Profile/components/ConfirmLogoutPopup.tsx
Labels: ✨ Feature

#99 fix: 서버 이벤트에 따른 소켓 동작 수정
  Frontend/src/App.tsx
  Frontend/src/contexts/WebSocketProvider.tsx
Labels: 🐞 BugFix

#100 refactor: AppRoutes 파일 따로 분기하여 라우트 관련 코드 깔끔하게 분리
  Frontend/package-lock.json
  Frontend/src/App.tsx
  Frontend/src/AppRoutes.tsx
  Frontend/src/main.tsx
  Frontend/src/pages/Profile/Profile.tsx
  Frontend/src/pages/Profile/components/ProfileSection.tsx
Labels: 🔨 Refactor

#101 Hyehan/friend list page socket
  Frontend/src/pages/FriendList/components/AlarmPopup.tsx
  package-lock.json
Labels: 🐞 BugFix, 📬 API
